version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - ./db:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin1234..
      WORDPRESS_DB_NAME: wordpress
    networks:
      - mi-red-interna
  db:
    image: mysql:8
    volumes:
      - ./db/DB:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: admin1234..
    networks:
      - mi-red-interna
networks:
  mi-red-interna:
    driver: bridge
    ipam:
      config:
        - subnet: 100.100.0.0/16
