version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    volumes:
      - ./db:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin1234..
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:8
    volumes:
      - ./db/DB:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: admin1234..

